name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make GitHub Secrets files
        run: |
          cat <<EOF > ./src/main/resources/google-stt-key.json
          ${{ secrets.GOOGLE_STT_KEY }}
          EOF
        shell: bash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build BootJar
        run: ./gradlew clean bootJar -x test --no-daemon

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app.jar
          path: build/libs/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app.jar
          path: .

      - uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/olllim:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/olllim:latest

  deploy:
    needs: docker # docker job이 성공해야 실행됨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Copy Docker Compose & Script to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USERNAME }}
          key: ${{ secrets.RELEASE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/"
          
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RELEASE_HOST }} 
          username: ${{ secrets.RELEASE_USERNAME }}
          key: ${{ secrets.RELEASE_KEY }} 
          port: 22
          script: |
            echo "${{ secrets.ENV_PROD }}" > /home/ubuntu/.env.prod
            
            # 배포 스크립트 실행
            sudo chmod +x /home/ubuntu/deploy.sh
            sudo /home/ubuntu/deploy.sh
